//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\work\\ReoScript\\ReoScript.g 2013-02-08 22:21:21

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  Unvell.ReoScript 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class ReoScriptLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__95=95;
	public const int T__96=96;
	public const int T__97=97;
	public const int T__98=98;
	public const int T__99=99;
	public const int T__100=100;
	public const int T__101=101;
	public const int T__102=102;
	public const int T__103=103;
	public const int T__104=104;
	public const int T__105=105;
	public const int T__106=106;
	public const int T__107=107;
	public const int T__108=108;
	public const int T__109=109;
	public const int T__110=110;
	public const int T__111=111;
	public const int AND=4;
	public const int ANONYMOUS_FUNCTION_DEFINE=5;
	public const int ARGUMENT_LIST=6;
	public const int ARRAY_ACCESS=7;
	public const int ARRAY_LITERAL=8;
	public const int ASSIGNMENT=9;
	public const int ASSIGN_AND=10;
	public const int ASSIGN_DIV=11;
	public const int ASSIGN_LSHIFT=12;
	public const int ASSIGN_MINUS=13;
	public const int ASSIGN_MUL=14;
	public const int ASSIGN_OR=15;
	public const int ASSIGN_PLUS=16;
	public const int ASSIGN_REM=17;
	public const int ASSIGN_REV=18;
	public const int ASSIGN_RSHIFT=19;
	public const int BLOCK=20;
	public const int BREAK=21;
	public const int COLON=22;
	public const int COMBINE_OBJECT=23;
	public const int COMMA=24;
	public const int COMMENT=25;
	public const int CONDITION=26;
	public const int CONTINUE=27;
	public const int CREATE=28;
	public const int DECLARATION=29;
	public const int DECREMENT=30;
	public const int DELETE=31;
	public const int DIV=32;
	public const int DOT=33;
	public const int ELSE=34;
	public const int EQUALS=35;
	public const int ESCAPE_SEQUENCE=36;
	public const int FALSE=37;
	public const int FOREACH_STATEMENT=38;
	public const int FOR_BODY=39;
	public const int FOR_CONDITION=40;
	public const int FOR_INIT=41;
	public const int FOR_ITERATOR=42;
	public const int FOR_STATEMENT=43;
	public const int FUNCTION_CALL=44;
	public const int FUNCTION_DEFINE=45;
	public const int GREAT_EQUALS=46;
	public const int GREAT_THAN=47;
	public const int HEX_LITERATE=48;
	public const int IDENTIFIER=49;
	public const int IF_STATEMENT=50;
	public const int IMPORT=51;
	public const int INCREMENT=52;
	public const int LBRACE=53;
	public const int LCURLY=54;
	public const int LESS_EQUALS=55;
	public const int LESS_THAN=56;
	public const int LINE_COMMENT=57;
	public const int LOGICAL_AND=58;
	public const int LOGICAL_OR=59;
	public const int LPAREN=60;
	public const int LSHIFT=61;
	public const int MINUS=62;
	public const int MOD=63;
	public const int MUL=64;
	public const int NEWLINE=65;
	public const int NOT=66;
	public const int NOT_EQUALS=67;
	public const int NULL=68;
	public const int NUMBER_LITERATE=69;
	public const int OBJECT_LITERAL=70;
	public const int OR=71;
	public const int PARAMETER_DEFINES=72;
	public const int PLUS=73;
	public const int POST_UNARY_STEP=74;
	public const int PRE_UNARY=75;
	public const int PRE_UNARY_STEP=76;
	public const int PROPERTY_ACCESS=77;
	public const int RBRACE=78;
	public const int RCURLY=79;
	public const int RETURN=80;
	public const int RPAREN=81;
	public const int RSHIFT=82;
	public const int SEMI=83;
	public const int STRING_LITERATE=84;
	public const int SWITCH=85;
	public const int SWITCH_CASE=86;
	public const int SWITCH_CASE_ELSE=87;
	public const int THIS=88;
	public const int TRUE=89;
	public const int TYPE=90;
	public const int UNDEFINED=91;
	public const int WHILE_STATEMENT=92;
	public const int WS=93;
	public const int XOR=94;

    // delegates
    // delegators

	public ReoScriptLexer()
	{
		OnCreated();
	}

	public ReoScriptLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public ReoScriptLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\work\\ReoScript\\ReoScript.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_AND();
	partial void LeaveRule_AND();

	// $ANTLR start "AND"
	[GrammarRule("AND")]
	private void mAND()
	{
		EnterRule_AND();
		EnterRule("AND", 1);
		TraceIn("AND", 1);
		try
		{
			int _type = AND;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:10:5: ( '&' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:10:7: '&'
			{
			DebugLocation(10, 7);
			Match('&'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AND", 1);
			LeaveRule("AND", 1);
			LeaveRule_AND();
		}
	}
	// $ANTLR end "AND"

	partial void EnterRule_DIV();
	partial void LeaveRule_DIV();

	// $ANTLR start "DIV"
	[GrammarRule("DIV")]
	private void mDIV()
	{
		EnterRule_DIV();
		EnterRule("DIV", 2);
		TraceIn("DIV", 2);
		try
		{
			int _type = DIV;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:11:5: ( '/' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:11:7: '/'
			{
			DebugLocation(11, 7);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIV", 2);
			LeaveRule("DIV", 2);
			LeaveRule_DIV();
		}
	}
	// $ANTLR end "DIV"

	partial void EnterRule_EQUALS();
	partial void LeaveRule_EQUALS();

	// $ANTLR start "EQUALS"
	[GrammarRule("EQUALS")]
	private void mEQUALS()
	{
		EnterRule_EQUALS();
		EnterRule("EQUALS", 3);
		TraceIn("EQUALS", 3);
		try
		{
			int _type = EQUALS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:12:8: ( '==' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:12:10: '=='
			{
			DebugLocation(12, 10);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EQUALS", 3);
			LeaveRule("EQUALS", 3);
			LeaveRule_EQUALS();
		}
	}
	// $ANTLR end "EQUALS"

	partial void EnterRule_GREAT_EQUALS();
	partial void LeaveRule_GREAT_EQUALS();

	// $ANTLR start "GREAT_EQUALS"
	[GrammarRule("GREAT_EQUALS")]
	private void mGREAT_EQUALS()
	{
		EnterRule_GREAT_EQUALS();
		EnterRule("GREAT_EQUALS", 4);
		TraceIn("GREAT_EQUALS", 4);
		try
		{
			int _type = GREAT_EQUALS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:13:14: ( '>=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:13:16: '>='
			{
			DebugLocation(13, 16);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("GREAT_EQUALS", 4);
			LeaveRule("GREAT_EQUALS", 4);
			LeaveRule_GREAT_EQUALS();
		}
	}
	// $ANTLR end "GREAT_EQUALS"

	partial void EnterRule_GREAT_THAN();
	partial void LeaveRule_GREAT_THAN();

	// $ANTLR start "GREAT_THAN"
	[GrammarRule("GREAT_THAN")]
	private void mGREAT_THAN()
	{
		EnterRule_GREAT_THAN();
		EnterRule("GREAT_THAN", 5);
		TraceIn("GREAT_THAN", 5);
		try
		{
			int _type = GREAT_THAN;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:14:12: ( '>' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:14:14: '>'
			{
			DebugLocation(14, 14);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("GREAT_THAN", 5);
			LeaveRule("GREAT_THAN", 5);
			LeaveRule_GREAT_THAN();
		}
	}
	// $ANTLR end "GREAT_THAN"

	partial void EnterRule_LESS_EQUALS();
	partial void LeaveRule_LESS_EQUALS();

	// $ANTLR start "LESS_EQUALS"
	[GrammarRule("LESS_EQUALS")]
	private void mLESS_EQUALS()
	{
		EnterRule_LESS_EQUALS();
		EnterRule("LESS_EQUALS", 6);
		TraceIn("LESS_EQUALS", 6);
		try
		{
			int _type = LESS_EQUALS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:15:13: ( '<=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:15:15: '<='
			{
			DebugLocation(15, 15);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LESS_EQUALS", 6);
			LeaveRule("LESS_EQUALS", 6);
			LeaveRule_LESS_EQUALS();
		}
	}
	// $ANTLR end "LESS_EQUALS"

	partial void EnterRule_LESS_THAN();
	partial void LeaveRule_LESS_THAN();

	// $ANTLR start "LESS_THAN"
	[GrammarRule("LESS_THAN")]
	private void mLESS_THAN()
	{
		EnterRule_LESS_THAN();
		EnterRule("LESS_THAN", 7);
		TraceIn("LESS_THAN", 7);
		try
		{
			int _type = LESS_THAN;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:16:11: ( '<' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:16:13: '<'
			{
			DebugLocation(16, 13);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LESS_THAN", 7);
			LeaveRule("LESS_THAN", 7);
			LeaveRule_LESS_THAN();
		}
	}
	// $ANTLR end "LESS_THAN"

	partial void EnterRule_LOGICAL_AND();
	partial void LeaveRule_LOGICAL_AND();

	// $ANTLR start "LOGICAL_AND"
	[GrammarRule("LOGICAL_AND")]
	private void mLOGICAL_AND()
	{
		EnterRule_LOGICAL_AND();
		EnterRule("LOGICAL_AND", 8);
		TraceIn("LOGICAL_AND", 8);
		try
		{
			int _type = LOGICAL_AND;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:17:13: ( '&&' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:17:15: '&&'
			{
			DebugLocation(17, 15);
			Match("&&"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LOGICAL_AND", 8);
			LeaveRule("LOGICAL_AND", 8);
			LeaveRule_LOGICAL_AND();
		}
	}
	// $ANTLR end "LOGICAL_AND"

	partial void EnterRule_LOGICAL_OR();
	partial void LeaveRule_LOGICAL_OR();

	// $ANTLR start "LOGICAL_OR"
	[GrammarRule("LOGICAL_OR")]
	private void mLOGICAL_OR()
	{
		EnterRule_LOGICAL_OR();
		EnterRule("LOGICAL_OR", 9);
		TraceIn("LOGICAL_OR", 9);
		try
		{
			int _type = LOGICAL_OR;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:18:12: ( '||' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:18:14: '||'
			{
			DebugLocation(18, 14);
			Match("||"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LOGICAL_OR", 9);
			LeaveRule("LOGICAL_OR", 9);
			LeaveRule_LOGICAL_OR();
		}
	}
	// $ANTLR end "LOGICAL_OR"

	partial void EnterRule_LSHIFT();
	partial void LeaveRule_LSHIFT();

	// $ANTLR start "LSHIFT"
	[GrammarRule("LSHIFT")]
	private void mLSHIFT()
	{
		EnterRule_LSHIFT();
		EnterRule("LSHIFT", 10);
		TraceIn("LSHIFT", 10);
		try
		{
			int _type = LSHIFT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:19:8: ( '<<' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:19:10: '<<'
			{
			DebugLocation(19, 10);
			Match("<<"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LSHIFT", 10);
			LeaveRule("LSHIFT", 10);
			LeaveRule_LSHIFT();
		}
	}
	// $ANTLR end "LSHIFT"

	partial void EnterRule_MINUS();
	partial void LeaveRule_MINUS();

	// $ANTLR start "MINUS"
	[GrammarRule("MINUS")]
	private void mMINUS()
	{
		EnterRule_MINUS();
		EnterRule("MINUS", 11);
		TraceIn("MINUS", 11);
		try
		{
			int _type = MINUS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:20:7: ( '-' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:20:9: '-'
			{
			DebugLocation(20, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MINUS", 11);
			LeaveRule("MINUS", 11);
			LeaveRule_MINUS();
		}
	}
	// $ANTLR end "MINUS"

	partial void EnterRule_MOD();
	partial void LeaveRule_MOD();

	// $ANTLR start "MOD"
	[GrammarRule("MOD")]
	private void mMOD()
	{
		EnterRule_MOD();
		EnterRule("MOD", 12);
		TraceIn("MOD", 12);
		try
		{
			int _type = MOD;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:21:5: ( '%' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:21:7: '%'
			{
			DebugLocation(21, 7);
			Match('%'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MOD", 12);
			LeaveRule("MOD", 12);
			LeaveRule_MOD();
		}
	}
	// $ANTLR end "MOD"

	partial void EnterRule_MUL();
	partial void LeaveRule_MUL();

	// $ANTLR start "MUL"
	[GrammarRule("MUL")]
	private void mMUL()
	{
		EnterRule_MUL();
		EnterRule("MUL", 13);
		TraceIn("MUL", 13);
		try
		{
			int _type = MUL;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:22:5: ( '*' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:22:7: '*'
			{
			DebugLocation(22, 7);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MUL", 13);
			LeaveRule("MUL", 13);
			LeaveRule_MUL();
		}
	}
	// $ANTLR end "MUL"

	partial void EnterRule_NOT_EQUALS();
	partial void LeaveRule_NOT_EQUALS();

	// $ANTLR start "NOT_EQUALS"
	[GrammarRule("NOT_EQUALS")]
	private void mNOT_EQUALS()
	{
		EnterRule_NOT_EQUALS();
		EnterRule("NOT_EQUALS", 14);
		TraceIn("NOT_EQUALS", 14);
		try
		{
			int _type = NOT_EQUALS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:23:12: ( '!=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:23:14: '!='
			{
			DebugLocation(23, 14);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NOT_EQUALS", 14);
			LeaveRule("NOT_EQUALS", 14);
			LeaveRule_NOT_EQUALS();
		}
	}
	// $ANTLR end "NOT_EQUALS"

	partial void EnterRule_OR();
	partial void LeaveRule_OR();

	// $ANTLR start "OR"
	[GrammarRule("OR")]
	private void mOR()
	{
		EnterRule_OR();
		EnterRule("OR", 15);
		TraceIn("OR", 15);
		try
		{
			int _type = OR;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:24:4: ( '|' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:24:6: '|'
			{
			DebugLocation(24, 6);
			Match('|'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OR", 15);
			LeaveRule("OR", 15);
			LeaveRule_OR();
		}
	}
	// $ANTLR end "OR"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 16);
		TraceIn("PLUS", 16);
		try
		{
			int _type = PLUS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:25:6: ( '+' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:25:8: '+'
			{
			DebugLocation(25, 8);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PLUS", 16);
			LeaveRule("PLUS", 16);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_RSHIFT();
	partial void LeaveRule_RSHIFT();

	// $ANTLR start "RSHIFT"
	[GrammarRule("RSHIFT")]
	private void mRSHIFT()
	{
		EnterRule_RSHIFT();
		EnterRule("RSHIFT", 17);
		TraceIn("RSHIFT", 17);
		try
		{
			int _type = RSHIFT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:26:8: ( '>>' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:26:10: '>>'
			{
			DebugLocation(26, 10);
			Match(">>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RSHIFT", 17);
			LeaveRule("RSHIFT", 17);
			LeaveRule_RSHIFT();
		}
	}
	// $ANTLR end "RSHIFT"

	partial void EnterRule_XOR();
	partial void LeaveRule_XOR();

	// $ANTLR start "XOR"
	[GrammarRule("XOR")]
	private void mXOR()
	{
		EnterRule_XOR();
		EnterRule("XOR", 18);
		TraceIn("XOR", 18);
		try
		{
			int _type = XOR;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:27:5: ( '^' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:27:7: '^'
			{
			DebugLocation(27, 7);
			Match('^'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("XOR", 18);
			LeaveRule("XOR", 18);
			LeaveRule_XOR();
		}
	}
	// $ANTLR end "XOR"

	partial void EnterRule_T__95();
	partial void LeaveRule_T__95();

	// $ANTLR start "T__95"
	[GrammarRule("T__95")]
	private void mT__95()
	{
		EnterRule_T__95();
		EnterRule("T__95", 19);
		TraceIn("T__95", 19);
		try
		{
			int _type = T__95;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:28:7: ( '=>' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:28:9: '=>'
			{
			DebugLocation(28, 9);
			Match("=>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__95", 19);
			LeaveRule("T__95", 19);
			LeaveRule_T__95();
		}
	}
	// $ANTLR end "T__95"

	partial void EnterRule_T__96();
	partial void LeaveRule_T__96();

	// $ANTLR start "T__96"
	[GrammarRule("T__96")]
	private void mT__96()
	{
		EnterRule_T__96();
		EnterRule("T__96", 20);
		TraceIn("T__96", 20);
		try
		{
			int _type = T__96;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:29:7: ( 'break' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:29:9: 'break'
			{
			DebugLocation(29, 9);
			Match("break"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__96", 20);
			LeaveRule("T__96", 20);
			LeaveRule_T__96();
		}
	}
	// $ANTLR end "T__96"

	partial void EnterRule_T__97();
	partial void LeaveRule_T__97();

	// $ANTLR start "T__97"
	[GrammarRule("T__97")]
	private void mT__97()
	{
		EnterRule_T__97();
		EnterRule("T__97", 21);
		TraceIn("T__97", 21);
		try
		{
			int _type = T__97;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:30:7: ( 'case' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:30:9: 'case'
			{
			DebugLocation(30, 9);
			Match("case"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__97", 21);
			LeaveRule("T__97", 21);
			LeaveRule_T__97();
		}
	}
	// $ANTLR end "T__97"

	partial void EnterRule_T__98();
	partial void LeaveRule_T__98();

	// $ANTLR start "T__98"
	[GrammarRule("T__98")]
	private void mT__98()
	{
		EnterRule_T__98();
		EnterRule("T__98", 22);
		TraceIn("T__98", 22);
		try
		{
			int _type = T__98;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:31:7: ( 'continue' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:31:9: 'continue'
			{
			DebugLocation(31, 9);
			Match("continue"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__98", 22);
			LeaveRule("T__98", 22);
			LeaveRule_T__98();
		}
	}
	// $ANTLR end "T__98"

	partial void EnterRule_T__99();
	partial void LeaveRule_T__99();

	// $ANTLR start "T__99"
	[GrammarRule("T__99")]
	private void mT__99()
	{
		EnterRule_T__99();
		EnterRule("T__99", 23);
		TraceIn("T__99", 23);
		try
		{
			int _type = T__99;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:32:7: ( 'default' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:32:9: 'default'
			{
			DebugLocation(32, 9);
			Match("default"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__99", 23);
			LeaveRule("T__99", 23);
			LeaveRule_T__99();
		}
	}
	// $ANTLR end "T__99"

	partial void EnterRule_T__100();
	partial void LeaveRule_T__100();

	// $ANTLR start "T__100"
	[GrammarRule("T__100")]
	private void mT__100()
	{
		EnterRule_T__100();
		EnterRule("T__100", 24);
		TraceIn("T__100", 24);
		try
		{
			int _type = T__100;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:33:8: ( 'delete' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:33:10: 'delete'
			{
			DebugLocation(33, 10);
			Match("delete"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__100", 24);
			LeaveRule("T__100", 24);
			LeaveRule_T__100();
		}
	}
	// $ANTLR end "T__100"

	partial void EnterRule_T__101();
	partial void LeaveRule_T__101();

	// $ANTLR start "T__101"
	[GrammarRule("T__101")]
	private void mT__101()
	{
		EnterRule_T__101();
		EnterRule("T__101", 25);
		TraceIn("T__101", 25);
		try
		{
			int _type = T__101;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:34:8: ( 'for' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:34:10: 'for'
			{
			DebugLocation(34, 10);
			Match("for"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__101", 25);
			LeaveRule("T__101", 25);
			LeaveRule_T__101();
		}
	}
	// $ANTLR end "T__101"

	partial void EnterRule_T__102();
	partial void LeaveRule_T__102();

	// $ANTLR start "T__102"
	[GrammarRule("T__102")]
	private void mT__102()
	{
		EnterRule_T__102();
		EnterRule("T__102", 26);
		TraceIn("T__102", 26);
		try
		{
			int _type = T__102;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:35:8: ( 'foreach' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:35:10: 'foreach'
			{
			DebugLocation(35, 10);
			Match("foreach"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__102", 26);
			LeaveRule("T__102", 26);
			LeaveRule_T__102();
		}
	}
	// $ANTLR end "T__102"

	partial void EnterRule_T__103();
	partial void LeaveRule_T__103();

	// $ANTLR start "T__103"
	[GrammarRule("T__103")]
	private void mT__103()
	{
		EnterRule_T__103();
		EnterRule("T__103", 27);
		TraceIn("T__103", 27);
		try
		{
			int _type = T__103;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:36:8: ( 'function' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:36:10: 'function'
			{
			DebugLocation(36, 10);
			Match("function"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__103", 27);
			LeaveRule("T__103", 27);
			LeaveRule_T__103();
		}
	}
	// $ANTLR end "T__103"

	partial void EnterRule_T__104();
	partial void LeaveRule_T__104();

	// $ANTLR start "T__104"
	[GrammarRule("T__104")]
	private void mT__104()
	{
		EnterRule_T__104();
		EnterRule("T__104", 28);
		TraceIn("T__104", 28);
		try
		{
			int _type = T__104;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:37:8: ( 'if' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:37:10: 'if'
			{
			DebugLocation(37, 10);
			Match("if"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__104", 28);
			LeaveRule("T__104", 28);
			LeaveRule_T__104();
		}
	}
	// $ANTLR end "T__104"

	partial void EnterRule_T__105();
	partial void LeaveRule_T__105();

	// $ANTLR start "T__105"
	[GrammarRule("T__105")]
	private void mT__105()
	{
		EnterRule_T__105();
		EnterRule("T__105", 29);
		TraceIn("T__105", 29);
		try
		{
			int _type = T__105;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:38:8: ( 'import' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:38:10: 'import'
			{
			DebugLocation(38, 10);
			Match("import"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__105", 29);
			LeaveRule("T__105", 29);
			LeaveRule_T__105();
		}
	}
	// $ANTLR end "T__105"

	partial void EnterRule_T__106();
	partial void LeaveRule_T__106();

	// $ANTLR start "T__106"
	[GrammarRule("T__106")]
	private void mT__106()
	{
		EnterRule_T__106();
		EnterRule("T__106", 30);
		TraceIn("T__106", 30);
		try
		{
			int _type = T__106;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:39:8: ( 'in' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:39:10: 'in'
			{
			DebugLocation(39, 10);
			Match("in"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__106", 30);
			LeaveRule("T__106", 30);
			LeaveRule_T__106();
		}
	}
	// $ANTLR end "T__106"

	partial void EnterRule_T__107();
	partial void LeaveRule_T__107();

	// $ANTLR start "T__107"
	[GrammarRule("T__107")]
	private void mT__107()
	{
		EnterRule_T__107();
		EnterRule("T__107", 31);
		TraceIn("T__107", 31);
		try
		{
			int _type = T__107;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:40:8: ( 'new' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:40:10: 'new'
			{
			DebugLocation(40, 10);
			Match("new"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__107", 31);
			LeaveRule("T__107", 31);
			LeaveRule_T__107();
		}
	}
	// $ANTLR end "T__107"

	partial void EnterRule_T__108();
	partial void LeaveRule_T__108();

	// $ANTLR start "T__108"
	[GrammarRule("T__108")]
	private void mT__108()
	{
		EnterRule_T__108();
		EnterRule("T__108", 32);
		TraceIn("T__108", 32);
		try
		{
			int _type = T__108;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:41:8: ( 'return' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:41:10: 'return'
			{
			DebugLocation(41, 10);
			Match("return"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__108", 32);
			LeaveRule("T__108", 32);
			LeaveRule_T__108();
		}
	}
	// $ANTLR end "T__108"

	partial void EnterRule_T__109();
	partial void LeaveRule_T__109();

	// $ANTLR start "T__109"
	[GrammarRule("T__109")]
	private void mT__109()
	{
		EnterRule_T__109();
		EnterRule("T__109", 33);
		TraceIn("T__109", 33);
		try
		{
			int _type = T__109;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:42:8: ( 'switch' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:42:10: 'switch'
			{
			DebugLocation(42, 10);
			Match("switch"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__109", 33);
			LeaveRule("T__109", 33);
			LeaveRule_T__109();
		}
	}
	// $ANTLR end "T__109"

	partial void EnterRule_T__110();
	partial void LeaveRule_T__110();

	// $ANTLR start "T__110"
	[GrammarRule("T__110")]
	private void mT__110()
	{
		EnterRule_T__110();
		EnterRule("T__110", 34);
		TraceIn("T__110", 34);
		try
		{
			int _type = T__110;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:43:8: ( 'while' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:43:10: 'while'
			{
			DebugLocation(43, 10);
			Match("while"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__110", 34);
			LeaveRule("T__110", 34);
			LeaveRule_T__110();
		}
	}
	// $ANTLR end "T__110"

	partial void EnterRule_T__111();
	partial void LeaveRule_T__111();

	// $ANTLR start "T__111"
	[GrammarRule("T__111")]
	private void mT__111()
	{
		EnterRule_T__111();
		EnterRule("T__111", 35);
		TraceIn("T__111", 35);
		try
		{
			int _type = T__111;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:44:8: ( '~' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:44:10: '~'
			{
			DebugLocation(44, 10);
			Match('~'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__111", 35);
			LeaveRule("T__111", 35);
			LeaveRule_T__111();
		}
	}
	// $ANTLR end "T__111"

	partial void EnterRule_NUMBER_LITERATE();
	partial void LeaveRule_NUMBER_LITERATE();

	// $ANTLR start "NUMBER_LITERATE"
	[GrammarRule("NUMBER_LITERATE")]
	private void mNUMBER_LITERATE()
	{
		EnterRule_NUMBER_LITERATE();
		EnterRule("NUMBER_LITERATE", 36);
		TraceIn("NUMBER_LITERATE", 36);
		try
		{
			int _type = NUMBER_LITERATE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:370:2: ( ( ( '0' .. '9' )* '.' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:370:4: ( ( '0' .. '9' )* '.' )? ( '0' .. '9' )+
			{
			DebugLocation(370, 4);
			// C:\\work\\ReoScript\\ReoScript.g:370:4: ( ( '0' .. '9' )* '.' )?
			int alt2=2;
			try { DebugEnterSubRule(2);
			try { DebugEnterDecision(2, false);
			try
			{
				alt2 = dfa2.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\work\\ReoScript\\ReoScript.g:370:5: ( '0' .. '9' )* '.'
				{
				DebugLocation(370, 5);
				// C:\\work\\ReoScript\\ReoScript.g:370:5: ( '0' .. '9' )*
				try { DebugEnterSubRule(1);
				while (true)
				{
					int alt1=2;
					try { DebugEnterDecision(1, false);
					int LA1_0 = input.LA(1);

					if (((LA1_0>='0' && LA1_0<='9')))
					{
						alt1 = 1;
					}


					} finally { DebugExitDecision(1); }
					switch ( alt1 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\work\\ReoScript\\ReoScript.g:
						{
						DebugLocation(370, 5);
						input.Consume();


						}
						break;

					default:
						goto loop1;
					}
				}

				loop1:
					;

				} finally { DebugExitSubRule(1); }

				DebugLocation(370, 16);
				Match('.'); 

				}
				break;

			}
			} finally { DebugExitSubRule(2); }

			DebugLocation(370, 21);
			// C:\\work\\ReoScript\\ReoScript.g:370:21: ( '0' .. '9' )+
			int cnt3=0;
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, false);
				int LA3_0 = input.LA(1);

				if (((LA3_0>='0' && LA3_0<='9')))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch (alt3)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:
					{
					DebugLocation(370, 21);
					input.Consume();


					}
					break;

				default:
					if (cnt3 >= 1)
						goto loop3;

					EarlyExitException eee3 = new EarlyExitException( 3, input );
					DebugRecognitionException(eee3);
					throw eee3;
				}
				cnt3++;
			}
			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMBER_LITERATE", 36);
			LeaveRule("NUMBER_LITERATE", 36);
			LeaveRule_NUMBER_LITERATE();
		}
	}
	// $ANTLR end "NUMBER_LITERATE"

	partial void EnterRule_HEX_LITERATE();
	partial void LeaveRule_HEX_LITERATE();

	// $ANTLR start "HEX_LITERATE"
	[GrammarRule("HEX_LITERATE")]
	private void mHEX_LITERATE()
	{
		EnterRule_HEX_LITERATE();
		EnterRule("HEX_LITERATE", 37);
		TraceIn("HEX_LITERATE", 37);
		try
		{
			int _type = HEX_LITERATE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:374:2: ( '0' 'x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:374:4: '0' 'x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			{
			DebugLocation(374, 4);
			Match('0'); 
			DebugLocation(374, 8);
			Match('x'); 
			DebugLocation(374, 12);
			// C:\\work\\ReoScript\\ReoScript.g:374:12: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_0 = input.LA(1);

				if (((LA4_0>='0' && LA4_0<='9')||(LA4_0>='A' && LA4_0<='F')||(LA4_0>='a' && LA4_0<='f')))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:
					{
					DebugLocation(374, 12);
					input.Consume();


					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("HEX_LITERATE", 37);
			LeaveRule("HEX_LITERATE", 37);
			LeaveRule_HEX_LITERATE();
		}
	}
	// $ANTLR end "HEX_LITERATE"

	partial void EnterRule_STRING_LITERATE();
	partial void LeaveRule_STRING_LITERATE();

	// $ANTLR start "STRING_LITERATE"
	[GrammarRule("STRING_LITERATE")]
	private void mSTRING_LITERATE()
	{
		EnterRule_STRING_LITERATE();
		EnterRule("STRING_LITERATE", 38);
		TraceIn("STRING_LITERATE", 38);
		try
		{
			int _type = STRING_LITERATE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:378:2: ( '\"' (~ '\"' )* '\"' | '\\'' (~ '\\'' )* '\\'' )
			int alt7=2;
			try { DebugEnterDecision(7, false);
			int LA7_0 = input.LA(1);

			if ((LA7_0=='\"'))
			{
				alt7 = 1;
			}
			else if ((LA7_0=='\''))
			{
				alt7 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 7, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\work\\ReoScript\\ReoScript.g:379:3: '\"' (~ '\"' )* '\"'
				{
				DebugLocation(379, 3);
				Match('\"'); 
				DebugLocation(379, 7);
				// C:\\work\\ReoScript\\ReoScript.g:379:7: (~ '\"' )*
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					int LA5_0 = input.LA(1);

					if (((LA5_0>='\u0000' && LA5_0<='!')||(LA5_0>='#' && LA5_0<='\uFFFF')))
					{
						alt5 = 1;
					}


					} finally { DebugExitDecision(5); }
					switch ( alt5 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\work\\ReoScript\\ReoScript.g:
						{
						DebugLocation(379, 7);
						input.Consume();


						}
						break;

					default:
						goto loop5;
					}
				}

				loop5:
					;

				} finally { DebugExitSubRule(5); }

				DebugLocation(379, 13);
				Match('\"'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\work\\ReoScript\\ReoScript.g:380:4: '\\'' (~ '\\'' )* '\\''
				{
				DebugLocation(380, 4);
				Match('\''); 
				DebugLocation(380, 9);
				// C:\\work\\ReoScript\\ReoScript.g:380:9: (~ '\\'' )*
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if (((LA6_0>='\u0000' && LA6_0<='&')||(LA6_0>='(' && LA6_0<='\uFFFF')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch ( alt6 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\work\\ReoScript\\ReoScript.g:
						{
						DebugLocation(380, 9);
						input.Consume();


						}
						break;

					default:
						goto loop6;
					}
				}

				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(380, 16);
				Match('\''); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING_LITERATE", 38);
			LeaveRule("STRING_LITERATE", 38);
			LeaveRule_STRING_LITERATE();
		}
	}
	// $ANTLR end "STRING_LITERATE"

	partial void EnterRule_ESCAPE_SEQUENCE();
	partial void LeaveRule_ESCAPE_SEQUENCE();

	// $ANTLR start "ESCAPE_SEQUENCE"
	[GrammarRule("ESCAPE_SEQUENCE")]
	private void mESCAPE_SEQUENCE()
	{
		EnterRule_ESCAPE_SEQUENCE();
		EnterRule("ESCAPE_SEQUENCE", 39);
		TraceIn("ESCAPE_SEQUENCE", 39);
		try
		{
			// C:\\work\\ReoScript\\ReoScript.g:388:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:388:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
			{
			DebugLocation(388, 9);
			Match('\\'); 
			DebugLocation(388, 14);
			if (input.LA(1)=='\"'||input.LA(1)=='\''||input.LA(1)=='\\'||input.LA(1)=='b'||input.LA(1)=='f'||input.LA(1)=='n'||input.LA(1)=='r'||input.LA(1)=='t')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("ESCAPE_SEQUENCE", 39);
			LeaveRule("ESCAPE_SEQUENCE", 39);
			LeaveRule_ESCAPE_SEQUENCE();
		}
	}
	// $ANTLR end "ESCAPE_SEQUENCE"

	partial void EnterRule_ASSIGNMENT();
	partial void LeaveRule_ASSIGNMENT();

	// $ANTLR start "ASSIGNMENT"
	[GrammarRule("ASSIGNMENT")]
	private void mASSIGNMENT()
	{
		EnterRule_ASSIGNMENT();
		EnterRule("ASSIGNMENT", 40);
		TraceIn("ASSIGNMENT", 40);
		try
		{
			int _type = ASSIGNMENT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:402:13: ( '=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:402:15: '='
			{
			DebugLocation(402, 15);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGNMENT", 40);
			LeaveRule("ASSIGNMENT", 40);
			LeaveRule_ASSIGNMENT();
		}
	}
	// $ANTLR end "ASSIGNMENT"

	partial void EnterRule_ASSIGN_PLUS();
	partial void LeaveRule_ASSIGN_PLUS();

	// $ANTLR start "ASSIGN_PLUS"
	[GrammarRule("ASSIGN_PLUS")]
	private void mASSIGN_PLUS()
	{
		EnterRule_ASSIGN_PLUS();
		EnterRule("ASSIGN_PLUS", 41);
		TraceIn("ASSIGN_PLUS", 41);
		try
		{
			int _type = ASSIGN_PLUS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:399:14: ( '+=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:399:16: '+='
			{
			DebugLocation(399, 16);
			Match("+="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_PLUS", 41);
			LeaveRule("ASSIGN_PLUS", 41);
			LeaveRule_ASSIGN_PLUS();
		}
	}
	// $ANTLR end "ASSIGN_PLUS"

	partial void EnterRule_ASSIGN_MINUS();
	partial void LeaveRule_ASSIGN_MINUS();

	// $ANTLR start "ASSIGN_MINUS"
	[GrammarRule("ASSIGN_MINUS")]
	private void mASSIGN_MINUS()
	{
		EnterRule_ASSIGN_MINUS();
		EnterRule("ASSIGN_MINUS", 42);
		TraceIn("ASSIGN_MINUS", 42);
		try
		{
			int _type = ASSIGN_MINUS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:400:14: ( '-=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:400:16: '-='
			{
			DebugLocation(400, 16);
			Match("-="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_MINUS", 42);
			LeaveRule("ASSIGN_MINUS", 42);
			LeaveRule_ASSIGN_MINUS();
		}
	}
	// $ANTLR end "ASSIGN_MINUS"

	partial void EnterRule_ASSIGN_MUL();
	partial void LeaveRule_ASSIGN_MUL();

	// $ANTLR start "ASSIGN_MUL"
	[GrammarRule("ASSIGN_MUL")]
	private void mASSIGN_MUL()
	{
		EnterRule_ASSIGN_MUL();
		EnterRule("ASSIGN_MUL", 43);
		TraceIn("ASSIGN_MUL", 43);
		try
		{
			int _type = ASSIGN_MUL;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:401:13: ( '*=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:401:15: '*='
			{
			DebugLocation(401, 15);
			Match("*="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_MUL", 43);
			LeaveRule("ASSIGN_MUL", 43);
			LeaveRule_ASSIGN_MUL();
		}
	}
	// $ANTLR end "ASSIGN_MUL"

	partial void EnterRule_ASSIGN_DIV();
	partial void LeaveRule_ASSIGN_DIV();

	// $ANTLR start "ASSIGN_DIV"
	[GrammarRule("ASSIGN_DIV")]
	private void mASSIGN_DIV()
	{
		EnterRule_ASSIGN_DIV();
		EnterRule("ASSIGN_DIV", 44);
		TraceIn("ASSIGN_DIV", 44);
		try
		{
			int _type = ASSIGN_DIV;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:402:13: ( '/=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:402:15: '/='
			{
			DebugLocation(402, 15);
			Match("/="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_DIV", 44);
			LeaveRule("ASSIGN_DIV", 44);
			LeaveRule_ASSIGN_DIV();
		}
	}
	// $ANTLR end "ASSIGN_DIV"

	partial void EnterRule_ASSIGN_REM();
	partial void LeaveRule_ASSIGN_REM();

	// $ANTLR start "ASSIGN_REM"
	[GrammarRule("ASSIGN_REM")]
	private void mASSIGN_REM()
	{
		EnterRule_ASSIGN_REM();
		EnterRule("ASSIGN_REM", 45);
		TraceIn("ASSIGN_REM", 45);
		try
		{
			int _type = ASSIGN_REM;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:403:13: ( '%=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:403:15: '%='
			{
			DebugLocation(403, 15);
			Match("%="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_REM", 45);
			LeaveRule("ASSIGN_REM", 45);
			LeaveRule_ASSIGN_REM();
		}
	}
	// $ANTLR end "ASSIGN_REM"

	partial void EnterRule_ASSIGN_AND();
	partial void LeaveRule_ASSIGN_AND();

	// $ANTLR start "ASSIGN_AND"
	[GrammarRule("ASSIGN_AND")]
	private void mASSIGN_AND()
	{
		EnterRule_ASSIGN_AND();
		EnterRule("ASSIGN_AND", 46);
		TraceIn("ASSIGN_AND", 46);
		try
		{
			int _type = ASSIGN_AND;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:404:13: ( '&=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:404:15: '&='
			{
			DebugLocation(404, 15);
			Match("&="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_AND", 46);
			LeaveRule("ASSIGN_AND", 46);
			LeaveRule_ASSIGN_AND();
		}
	}
	// $ANTLR end "ASSIGN_AND"

	partial void EnterRule_ASSIGN_OR();
	partial void LeaveRule_ASSIGN_OR();

	// $ANTLR start "ASSIGN_OR"
	[GrammarRule("ASSIGN_OR")]
	private void mASSIGN_OR()
	{
		EnterRule_ASSIGN_OR();
		EnterRule("ASSIGN_OR", 47);
		TraceIn("ASSIGN_OR", 47);
		try
		{
			int _type = ASSIGN_OR;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:405:12: ( '|=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:405:14: '|='
			{
			DebugLocation(405, 14);
			Match("|="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_OR", 47);
			LeaveRule("ASSIGN_OR", 47);
			LeaveRule_ASSIGN_OR();
		}
	}
	// $ANTLR end "ASSIGN_OR"

	partial void EnterRule_ASSIGN_REV();
	partial void LeaveRule_ASSIGN_REV();

	// $ANTLR start "ASSIGN_REV"
	[GrammarRule("ASSIGN_REV")]
	private void mASSIGN_REV()
	{
		EnterRule_ASSIGN_REV();
		EnterRule("ASSIGN_REV", 48);
		TraceIn("ASSIGN_REV", 48);
		try
		{
			int _type = ASSIGN_REV;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:406:13: ( '^=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:406:15: '^='
			{
			DebugLocation(406, 15);
			Match("^="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_REV", 48);
			LeaveRule("ASSIGN_REV", 48);
			LeaveRule_ASSIGN_REV();
		}
	}
	// $ANTLR end "ASSIGN_REV"

	partial void EnterRule_ASSIGN_LSHIFT();
	partial void LeaveRule_ASSIGN_LSHIFT();

	// $ANTLR start "ASSIGN_LSHIFT"
	[GrammarRule("ASSIGN_LSHIFT")]
	private void mASSIGN_LSHIFT()
	{
		EnterRule_ASSIGN_LSHIFT();
		EnterRule("ASSIGN_LSHIFT", 49);
		TraceIn("ASSIGN_LSHIFT", 49);
		try
		{
			int _type = ASSIGN_LSHIFT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:407:15: ( '<<=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:407:17: '<<='
			{
			DebugLocation(407, 17);
			Match("<<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_LSHIFT", 49);
			LeaveRule("ASSIGN_LSHIFT", 49);
			LeaveRule_ASSIGN_LSHIFT();
		}
	}
	// $ANTLR end "ASSIGN_LSHIFT"

	partial void EnterRule_ASSIGN_RSHIFT();
	partial void LeaveRule_ASSIGN_RSHIFT();

	// $ANTLR start "ASSIGN_RSHIFT"
	[GrammarRule("ASSIGN_RSHIFT")]
	private void mASSIGN_RSHIFT()
	{
		EnterRule_ASSIGN_RSHIFT();
		EnterRule("ASSIGN_RSHIFT", 50);
		TraceIn("ASSIGN_RSHIFT", 50);
		try
		{
			int _type = ASSIGN_RSHIFT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:408:15: ( '>>=' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:408:17: '>>='
			{
			DebugLocation(408, 17);
			Match(">>="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN_RSHIFT", 50);
			LeaveRule("ASSIGN_RSHIFT", 50);
			LeaveRule_ASSIGN_RSHIFT();
		}
	}
	// $ANTLR end "ASSIGN_RSHIFT"

	partial void EnterRule_COMMA();
	partial void LeaveRule_COMMA();

	// $ANTLR start "COMMA"
	[GrammarRule("COMMA")]
	private void mCOMMA()
	{
		EnterRule_COMMA();
		EnterRule("COMMA", 51);
		TraceIn("COMMA", 51);
		try
		{
			int _type = COMMA;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:410:9: ( ',' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:410:11: ','
			{
			DebugLocation(410, 11);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMA", 51);
			LeaveRule("COMMA", 51);
			LeaveRule_COMMA();
		}
	}
	// $ANTLR end "COMMA"

	partial void EnterRule_LPAREN();
	partial void LeaveRule_LPAREN();

	// $ANTLR start "LPAREN"
	[GrammarRule("LPAREN")]
	private void mLPAREN()
	{
		EnterRule_LPAREN();
		EnterRule("LPAREN", 52);
		TraceIn("LPAREN", 52);
		try
		{
			int _type = LPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:411:10: ( '(' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:411:12: '('
			{
			DebugLocation(411, 12);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LPAREN", 52);
			LeaveRule("LPAREN", 52);
			LeaveRule_LPAREN();
		}
	}
	// $ANTLR end "LPAREN"

	partial void EnterRule_RPAREN();
	partial void LeaveRule_RPAREN();

	// $ANTLR start "RPAREN"
	[GrammarRule("RPAREN")]
	private void mRPAREN()
	{
		EnterRule_RPAREN();
		EnterRule("RPAREN", 53);
		TraceIn("RPAREN", 53);
		try
		{
			int _type = RPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:412:10: ( ')' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:412:12: ')'
			{
			DebugLocation(412, 12);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RPAREN", 53);
			LeaveRule("RPAREN", 53);
			LeaveRule_RPAREN();
		}
	}
	// $ANTLR end "RPAREN"

	partial void EnterRule_LBRACE();
	partial void LeaveRule_LBRACE();

	// $ANTLR start "LBRACE"
	[GrammarRule("LBRACE")]
	private void mLBRACE()
	{
		EnterRule_LBRACE();
		EnterRule("LBRACE", 54);
		TraceIn("LBRACE", 54);
		try
		{
			int _type = LBRACE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:413:10: ( '[' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:413:12: '['
			{
			DebugLocation(413, 12);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LBRACE", 54);
			LeaveRule("LBRACE", 54);
			LeaveRule_LBRACE();
		}
	}
	// $ANTLR end "LBRACE"

	partial void EnterRule_RBRACE();
	partial void LeaveRule_RBRACE();

	// $ANTLR start "RBRACE"
	[GrammarRule("RBRACE")]
	private void mRBRACE()
	{
		EnterRule_RBRACE();
		EnterRule("RBRACE", 55);
		TraceIn("RBRACE", 55);
		try
		{
			int _type = RBRACE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:414:10: ( ']' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:414:12: ']'
			{
			DebugLocation(414, 12);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RBRACE", 55);
			LeaveRule("RBRACE", 55);
			LeaveRule_RBRACE();
		}
	}
	// $ANTLR end "RBRACE"

	partial void EnterRule_LCURLY();
	partial void LeaveRule_LCURLY();

	// $ANTLR start "LCURLY"
	[GrammarRule("LCURLY")]
	private void mLCURLY()
	{
		EnterRule_LCURLY();
		EnterRule("LCURLY", 56);
		TraceIn("LCURLY", 56);
		try
		{
			int _type = LCURLY;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:415:10: ( '{' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:415:12: '{'
			{
			DebugLocation(415, 12);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LCURLY", 56);
			LeaveRule("LCURLY", 56);
			LeaveRule_LCURLY();
		}
	}
	// $ANTLR end "LCURLY"

	partial void EnterRule_RCURLY();
	partial void LeaveRule_RCURLY();

	// $ANTLR start "RCURLY"
	[GrammarRule("RCURLY")]
	private void mRCURLY()
	{
		EnterRule_RCURLY();
		EnterRule("RCURLY", 57);
		TraceIn("RCURLY", 57);
		try
		{
			int _type = RCURLY;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:416:10: ( '}' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:416:12: '}'
			{
			DebugLocation(416, 12);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RCURLY", 57);
			LeaveRule("RCURLY", 57);
			LeaveRule_RCURLY();
		}
	}
	// $ANTLR end "RCURLY"

	partial void EnterRule_COLON();
	partial void LeaveRule_COLON();

	// $ANTLR start "COLON"
	[GrammarRule("COLON")]
	private void mCOLON()
	{
		EnterRule_COLON();
		EnterRule("COLON", 58);
		TraceIn("COLON", 58);
		try
		{
			int _type = COLON;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:417:9: ( ':' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:417:11: ':'
			{
			DebugLocation(417, 11);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COLON", 58);
			LeaveRule("COLON", 58);
			LeaveRule_COLON();
		}
	}
	// $ANTLR end "COLON"

	partial void EnterRule_DOT();
	partial void LeaveRule_DOT();

	// $ANTLR start "DOT"
	[GrammarRule("DOT")]
	private void mDOT()
	{
		EnterRule_DOT();
		EnterRule("DOT", 59);
		TraceIn("DOT", 59);
		try
		{
			int _type = DOT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:418:8: ( '.' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:418:10: '.'
			{
			DebugLocation(418, 10);
			Match('.'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DOT", 59);
			LeaveRule("DOT", 59);
			LeaveRule_DOT();
		}
	}
	// $ANTLR end "DOT"

	partial void EnterRule_NOT();
	partial void LeaveRule_NOT();

	// $ANTLR start "NOT"
	[GrammarRule("NOT")]
	private void mNOT()
	{
		EnterRule_NOT();
		EnterRule("NOT", 60);
		TraceIn("NOT", 60);
		try
		{
			int _type = NOT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:419:8: ( '!' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:419:10: '!'
			{
			DebugLocation(419, 10);
			Match('!'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NOT", 60);
			LeaveRule("NOT", 60);
			LeaveRule_NOT();
		}
	}
	// $ANTLR end "NOT"

	partial void EnterRule_INCREMENT();
	partial void LeaveRule_INCREMENT();

	// $ANTLR start "INCREMENT"
	[GrammarRule("INCREMENT")]
	private void mINCREMENT()
	{
		EnterRule_INCREMENT();
		EnterRule("INCREMENT", 61);
		TraceIn("INCREMENT", 61);
		try
		{
			int _type = INCREMENT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:421:12: ( '++' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:421:14: '++'
			{
			DebugLocation(421, 14);
			Match("++"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INCREMENT", 61);
			LeaveRule("INCREMENT", 61);
			LeaveRule_INCREMENT();
		}
	}
	// $ANTLR end "INCREMENT"

	partial void EnterRule_DECREMENT();
	partial void LeaveRule_DECREMENT();

	// $ANTLR start "DECREMENT"
	[GrammarRule("DECREMENT")]
	private void mDECREMENT()
	{
		EnterRule_DECREMENT();
		EnterRule("DECREMENT", 62);
		TraceIn("DECREMENT", 62);
		try
		{
			int _type = DECREMENT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:422:12: ( '--' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:422:14: '--'
			{
			DebugLocation(422, 14);
			Match("--"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DECREMENT", 62);
			LeaveRule("DECREMENT", 62);
			LeaveRule_DECREMENT();
		}
	}
	// $ANTLR end "DECREMENT"

	partial void EnterRule_CONDITION();
	partial void LeaveRule_CONDITION();

	// $ANTLR start "CONDITION"
	[GrammarRule("CONDITION")]
	private void mCONDITION()
	{
		EnterRule_CONDITION();
		EnterRule("CONDITION", 63);
		TraceIn("CONDITION", 63);
		try
		{
			int _type = CONDITION;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:424:12: ( '?' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:424:14: '?'
			{
			DebugLocation(424, 14);
			Match('?'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CONDITION", 63);
			LeaveRule("CONDITION", 63);
			LeaveRule_CONDITION();
		}
	}
	// $ANTLR end "CONDITION"

	partial void EnterRule_ELSE();
	partial void LeaveRule_ELSE();

	// $ANTLR start "ELSE"
	[GrammarRule("ELSE")]
	private void mELSE()
	{
		EnterRule_ELSE();
		EnterRule("ELSE", 64);
		TraceIn("ELSE", 64);
		try
		{
			int _type = ELSE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:425:8: ( 'else' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:425:10: 'else'
			{
			DebugLocation(425, 10);
			Match("else"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ELSE", 64);
			LeaveRule("ELSE", 64);
			LeaveRule_ELSE();
		}
	}
	// $ANTLR end "ELSE"

	partial void EnterRule_TYPE();
	partial void LeaveRule_TYPE();

	// $ANTLR start "TYPE"
	[GrammarRule("TYPE")]
	private void mTYPE()
	{
		EnterRule_TYPE();
		EnterRule("TYPE", 65);
		TraceIn("TYPE", 65);
		try
		{
			int _type = TYPE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:428:8: ( 'var' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:428:10: 'var'
			{
			DebugLocation(428, 10);
			Match("var"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TYPE", 65);
			LeaveRule("TYPE", 65);
			LeaveRule_TYPE();
		}
	}
	// $ANTLR end "TYPE"

	partial void EnterRule_TRUE();
	partial void LeaveRule_TRUE();

	// $ANTLR start "TRUE"
	[GrammarRule("TRUE")]
	private void mTRUE()
	{
		EnterRule_TRUE();
		EnterRule("TRUE", 66);
		TraceIn("TRUE", 66);
		try
		{
			int _type = TRUE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:429:8: ( 'true' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:429:10: 'true'
			{
			DebugLocation(429, 10);
			Match("true"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TRUE", 66);
			LeaveRule("TRUE", 66);
			LeaveRule_TRUE();
		}
	}
	// $ANTLR end "TRUE"

	partial void EnterRule_FALSE();
	partial void LeaveRule_FALSE();

	// $ANTLR start "FALSE"
	[GrammarRule("FALSE")]
	private void mFALSE()
	{
		EnterRule_FALSE();
		EnterRule("FALSE", 67);
		TraceIn("FALSE", 67);
		try
		{
			int _type = FALSE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:430:9: ( 'false' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:430:11: 'false'
			{
			DebugLocation(430, 11);
			Match("false"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FALSE", 67);
			LeaveRule("FALSE", 67);
			LeaveRule_FALSE();
		}
	}
	// $ANTLR end "FALSE"

	partial void EnterRule_NULL();
	partial void LeaveRule_NULL();

	// $ANTLR start "NULL"
	[GrammarRule("NULL")]
	private void mNULL()
	{
		EnterRule_NULL();
		EnterRule("NULL", 68);
		TraceIn("NULL", 68);
		try
		{
			int _type = NULL;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:431:8: ( 'null' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:431:10: 'null'
			{
			DebugLocation(431, 10);
			Match("null"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NULL", 68);
			LeaveRule("NULL", 68);
			LeaveRule_NULL();
		}
	}
	// $ANTLR end "NULL"

	partial void EnterRule_THIS();
	partial void LeaveRule_THIS();

	// $ANTLR start "THIS"
	[GrammarRule("THIS")]
	private void mTHIS()
	{
		EnterRule_THIS();
		EnterRule("THIS", 69);
		TraceIn("THIS", 69);
		try
		{
			int _type = THIS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:432:8: ( 'this' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:432:10: 'this'
			{
			DebugLocation(432, 10);
			Match("this"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("THIS", 69);
			LeaveRule("THIS", 69);
			LeaveRule_THIS();
		}
	}
	// $ANTLR end "THIS"

	partial void EnterRule_UNDEFINED();
	partial void LeaveRule_UNDEFINED();

	// $ANTLR start "UNDEFINED"
	[GrammarRule("UNDEFINED")]
	private void mUNDEFINED()
	{
		EnterRule_UNDEFINED();
		EnterRule("UNDEFINED", 70);
		TraceIn("UNDEFINED", 70);
		try
		{
			int _type = UNDEFINED;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:433:13: ( 'undefined' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:433:15: 'undefined'
			{
			DebugLocation(433, 15);
			Match("undefined"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("UNDEFINED", 70);
			LeaveRule("UNDEFINED", 70);
			LeaveRule_UNDEFINED();
		}
	}
	// $ANTLR end "UNDEFINED"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 71);
		TraceIn("COMMENT", 71);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:435:11: ( '/*' ( options {greedy=false; } : . )* '*/' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:435:13: '/*' ( options {greedy=false; } : . )* '*/'
			{
			DebugLocation(435, 13);
			Match("/*"); 

			DebugLocation(435, 18);
			// C:\\work\\ReoScript\\ReoScript.g:435:18: ( options {greedy=false; } : . )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_0 = input.LA(1);

				if ((LA8_0=='*'))
				{
					int LA8_1 = input.LA(2);

					if ((LA8_1=='/'))
					{
						alt8 = 2;
					}
					else if (((LA8_1>='\u0000' && LA8_1<='.')||(LA8_1>='0' && LA8_1<='\uFFFF')))
					{
						alt8 = 1;
					}


				}
				else if (((LA8_0>='\u0000' && LA8_0<=')')||(LA8_0>='+' && LA8_0<='\uFFFF')))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:435:45: .
					{
					DebugLocation(435, 45);
					MatchAny(); 

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }

			DebugLocation(435, 49);
			Match("*/"); 

			DebugLocation(435, 54);
			 _channel=HIDDEN; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 71);
			LeaveRule("COMMENT", 71);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	partial void EnterRule_LINE_COMMENT();
	partial void LeaveRule_LINE_COMMENT();

	// $ANTLR start "LINE_COMMENT"
	[GrammarRule("LINE_COMMENT")]
	private void mLINE_COMMENT()
	{
		EnterRule_LINE_COMMENT();
		EnterRule("LINE_COMMENT", 72);
		TraceIn("LINE_COMMENT", 72);
		try
		{
			int _type = LINE_COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:436:14: ( '//' (~ ( '\\r' | '\\n' ) )* )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:436:16: '//' (~ ( '\\r' | '\\n' ) )*
			{
			DebugLocation(436, 16);
			Match("//"); 

			DebugLocation(436, 21);
			// C:\\work\\ReoScript\\ReoScript.g:436:21: (~ ( '\\r' | '\\n' ) )*
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_0 = input.LA(1);

				if (((LA9_0>='\u0000' && LA9_0<='\t')||(LA9_0>='\u000B' && LA9_0<='\f')||(LA9_0>='\u000E' && LA9_0<='\uFFFF')))
				{
					alt9 = 1;
				}


				} finally { DebugExitDecision(9); }
				switch ( alt9 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:
					{
					DebugLocation(436, 21);
					input.Consume();


					}
					break;

				default:
					goto loop9;
				}
			}

			loop9:
				;

			} finally { DebugExitSubRule(9); }

			DebugLocation(436, 35);
			 _channel=HIDDEN; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LINE_COMMENT", 72);
			LeaveRule("LINE_COMMENT", 72);
			LeaveRule_LINE_COMMENT();
		}
	}
	// $ANTLR end "LINE_COMMENT"

	partial void EnterRule_IDENTIFIER();
	partial void LeaveRule_IDENTIFIER();

	// $ANTLR start "IDENTIFIER"
	[GrammarRule("IDENTIFIER")]
	private void mIDENTIFIER()
	{
		EnterRule_IDENTIFIER();
		EnterRule("IDENTIFIER", 73);
		TraceIn("IDENTIFIER", 73);
		try
		{
			int _type = IDENTIFIER;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:438:14: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' | '$' ) ( '0' .. '9' | 'a' .. 'z' | 'A' .. 'Z' | '_' )* )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:438:16: ( 'a' .. 'z' | 'A' .. 'Z' | '_' | '$' ) ( '0' .. '9' | 'a' .. 'z' | 'A' .. 'Z' | '_' )*
			{
			DebugLocation(438, 16);
			if (input.LA(1)=='$'||(input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(438, 44);
			// C:\\work\\ReoScript\\ReoScript.g:438:44: ( '0' .. '9' | 'a' .. 'z' | 'A' .. 'Z' | '_' )*
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_0 = input.LA(1);

				if (((LA10_0>='0' && LA10_0<='9')||(LA10_0>='A' && LA10_0<='Z')||LA10_0=='_'||(LA10_0>='a' && LA10_0<='z')))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch ( alt10 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:
					{
					DebugLocation(438, 44);
					input.Consume();


					}
					break;

				default:
					goto loop10;
				}
			}

			loop10:
				;

			} finally { DebugExitSubRule(10); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IDENTIFIER", 73);
			LeaveRule("IDENTIFIER", 73);
			LeaveRule_IDENTIFIER();
		}
	}
	// $ANTLR end "IDENTIFIER"

	partial void EnterRule_NEWLINE();
	partial void LeaveRule_NEWLINE();

	// $ANTLR start "NEWLINE"
	[GrammarRule("NEWLINE")]
	private void mNEWLINE()
	{
		EnterRule_NEWLINE();
		EnterRule("NEWLINE", 74);
		TraceIn("NEWLINE", 74);
		try
		{
			int _type = NEWLINE;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:439:11: ( ( '\\r' )? '\\n' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:439:13: ( '\\r' )? '\\n'
			{
			DebugLocation(439, 13);
			// C:\\work\\ReoScript\\ReoScript.g:439:13: ( '\\r' )?
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, false);
			int LA11_0 = input.LA(1);

			if ((LA11_0=='\r'))
			{
				alt11 = 1;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\work\\ReoScript\\ReoScript.g:439:13: '\\r'
				{
				DebugLocation(439, 13);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(11); }

			DebugLocation(439, 19);
			Match('\n'); 
			DebugLocation(439, 24);
			 _channel=HIDDEN; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NEWLINE", 74);
			LeaveRule("NEWLINE", 74);
			LeaveRule_NEWLINE();
		}
	}
	// $ANTLR end "NEWLINE"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 75);
		TraceIn("WS", 75);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:440:7: ( ( ' ' | '\\t' | NEWLINE )+ )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:440:9: ( ' ' | '\\t' | NEWLINE )+
			{
			DebugLocation(440, 9);
			// C:\\work\\ReoScript\\ReoScript.g:440:9: ( ' ' | '\\t' | NEWLINE )+
			int cnt12=0;
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=4;
				try { DebugEnterDecision(12, false);
				switch (input.LA(1))
				{
				case ' ':
					{
					alt12 = 1;
					}
					break;
				case '\t':
					{
					alt12 = 2;
					}
					break;
				case '\n':
				case '\r':
					{
					alt12 = 3;
					}
					break;
				}

				} finally { DebugExitDecision(12); }
				switch (alt12)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\work\\ReoScript\\ReoScript.g:440:10: ' '
					{
					DebugLocation(440, 10);
					Match(' '); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\work\\ReoScript\\ReoScript.g:440:14: '\\t'
					{
					DebugLocation(440, 14);
					Match('\t'); 

					}
					break;
				case 3:
					DebugEnterAlt(3);
					// C:\\work\\ReoScript\\ReoScript.g:440:21: NEWLINE
					{
					DebugLocation(440, 21);
					mNEWLINE(); 

					}
					break;

				default:
					if (cnt12 >= 1)
						goto loop12;

					EarlyExitException eee12 = new EarlyExitException( 12, input );
					DebugRecognitionException(eee12);
					throw eee12;
				}
				cnt12++;
			}
			loop12:
				;

			} finally { DebugExitSubRule(12); }

			DebugLocation(440, 32);
			 _channel=HIDDEN; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 75);
			LeaveRule("WS", 75);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_SEMI();
	partial void LeaveRule_SEMI();

	// $ANTLR start "SEMI"
	[GrammarRule("SEMI")]
	private void mSEMI()
	{
		EnterRule_SEMI();
		EnterRule("SEMI", 76);
		TraceIn("SEMI", 76);
		try
		{
			int _type = SEMI;
			int _channel = DefaultTokenChannel;
			// C:\\work\\ReoScript\\ReoScript.g:441:8: ( ';' )
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:441:10: ';'
			{
			DebugLocation(441, 10);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SEMI", 76);
			LeaveRule("SEMI", 76);
			LeaveRule_SEMI();
		}
	}
	// $ANTLR end "SEMI"

	public override void mTokens()
	{
		// C:\\work\\ReoScript\\ReoScript.g:1:8: ( AND | DIV | EQUALS | GREAT_EQUALS | GREAT_THAN | LESS_EQUALS | LESS_THAN | LOGICAL_AND | LOGICAL_OR | LSHIFT | MINUS | MOD | MUL | NOT_EQUALS | OR | PLUS | RSHIFT | XOR | T__95 | T__96 | T__97 | T__98 | T__99 | T__100 | T__101 | T__102 | T__103 | T__104 | T__105 | T__106 | T__107 | T__108 | T__109 | T__110 | T__111 | NUMBER_LITERATE | HEX_LITERATE | STRING_LITERATE | ASSIGNMENT | ASSIGN_PLUS | ASSIGN_MINUS | ASSIGN_MUL | ASSIGN_DIV | ASSIGN_REM | ASSIGN_AND | ASSIGN_OR | ASSIGN_REV | ASSIGN_LSHIFT | ASSIGN_RSHIFT | COMMA | LPAREN | RPAREN | LBRACE | RBRACE | LCURLY | RCURLY | COLON | DOT | NOT | INCREMENT | DECREMENT | CONDITION | ELSE | TYPE | TRUE | FALSE | NULL | THIS | UNDEFINED | COMMENT | LINE_COMMENT | IDENTIFIER | NEWLINE | WS | SEMI )
		int alt13=75;
		try { DebugEnterDecision(13, false);
		try
		{
			alt13 = dfa13.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(13); }
		switch (alt13)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\work\\ReoScript\\ReoScript.g:1:10: AND
			{
			DebugLocation(1, 10);
			mAND(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\work\\ReoScript\\ReoScript.g:1:14: DIV
			{
			DebugLocation(1, 14);
			mDIV(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\work\\ReoScript\\ReoScript.g:1:18: EQUALS
			{
			DebugLocation(1, 18);
			mEQUALS(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\work\\ReoScript\\ReoScript.g:1:25: GREAT_EQUALS
			{
			DebugLocation(1, 25);
			mGREAT_EQUALS(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\work\\ReoScript\\ReoScript.g:1:38: GREAT_THAN
			{
			DebugLocation(1, 38);
			mGREAT_THAN(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\work\\ReoScript\\ReoScript.g:1:49: LESS_EQUALS
			{
			DebugLocation(1, 49);
			mLESS_EQUALS(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\work\\ReoScript\\ReoScript.g:1:61: LESS_THAN
			{
			DebugLocation(1, 61);
			mLESS_THAN(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\work\\ReoScript\\ReoScript.g:1:71: LOGICAL_AND
			{
			DebugLocation(1, 71);
			mLOGICAL_AND(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\work\\ReoScript\\ReoScript.g:1:83: LOGICAL_OR
			{
			DebugLocation(1, 83);
			mLOGICAL_OR(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\work\\ReoScript\\ReoScript.g:1:94: LSHIFT
			{
			DebugLocation(1, 94);
			mLSHIFT(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\work\\ReoScript\\ReoScript.g:1:101: MINUS
			{
			DebugLocation(1, 101);
			mMINUS(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\work\\ReoScript\\ReoScript.g:1:107: MOD
			{
			DebugLocation(1, 107);
			mMOD(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\work\\ReoScript\\ReoScript.g:1:111: MUL
			{
			DebugLocation(1, 111);
			mMUL(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\work\\ReoScript\\ReoScript.g:1:115: NOT_EQUALS
			{
			DebugLocation(1, 115);
			mNOT_EQUALS(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\work\\ReoScript\\ReoScript.g:1:126: OR
			{
			DebugLocation(1, 126);
			mOR(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\work\\ReoScript\\ReoScript.g:1:129: PLUS
			{
			DebugLocation(1, 129);
			mPLUS(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\work\\ReoScript\\ReoScript.g:1:134: RSHIFT
			{
			DebugLocation(1, 134);
			mRSHIFT(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\work\\ReoScript\\ReoScript.g:1:141: XOR
			{
			DebugLocation(1, 141);
			mXOR(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// C:\\work\\ReoScript\\ReoScript.g:1:145: T__95
			{
			DebugLocation(1, 145);
			mT__95(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// C:\\work\\ReoScript\\ReoScript.g:1:151: T__96
			{
			DebugLocation(1, 151);
			mT__96(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// C:\\work\\ReoScript\\ReoScript.g:1:157: T__97
			{
			DebugLocation(1, 157);
			mT__97(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// C:\\work\\ReoScript\\ReoScript.g:1:163: T__98
			{
			DebugLocation(1, 163);
			mT__98(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// C:\\work\\ReoScript\\ReoScript.g:1:169: T__99
			{
			DebugLocation(1, 169);
			mT__99(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// C:\\work\\ReoScript\\ReoScript.g:1:175: T__100
			{
			DebugLocation(1, 175);
			mT__100(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// C:\\work\\ReoScript\\ReoScript.g:1:182: T__101
			{
			DebugLocation(1, 182);
			mT__101(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// C:\\work\\ReoScript\\ReoScript.g:1:189: T__102
			{
			DebugLocation(1, 189);
			mT__102(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// C:\\work\\ReoScript\\ReoScript.g:1:196: T__103
			{
			DebugLocation(1, 196);
			mT__103(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// C:\\work\\ReoScript\\ReoScript.g:1:203: T__104
			{
			DebugLocation(1, 203);
			mT__104(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// C:\\work\\ReoScript\\ReoScript.g:1:210: T__105
			{
			DebugLocation(1, 210);
			mT__105(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// C:\\work\\ReoScript\\ReoScript.g:1:217: T__106
			{
			DebugLocation(1, 217);
			mT__106(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// C:\\work\\ReoScript\\ReoScript.g:1:224: T__107
			{
			DebugLocation(1, 224);
			mT__107(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// C:\\work\\ReoScript\\ReoScript.g:1:231: T__108
			{
			DebugLocation(1, 231);
			mT__108(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// C:\\work\\ReoScript\\ReoScript.g:1:238: T__109
			{
			DebugLocation(1, 238);
			mT__109(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// C:\\work\\ReoScript\\ReoScript.g:1:245: T__110
			{
			DebugLocation(1, 245);
			mT__110(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// C:\\work\\ReoScript\\ReoScript.g:1:252: T__111
			{
			DebugLocation(1, 252);
			mT__111(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// C:\\work\\ReoScript\\ReoScript.g:1:259: NUMBER_LITERATE
			{
			DebugLocation(1, 259);
			mNUMBER_LITERATE(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// C:\\work\\ReoScript\\ReoScript.g:1:275: HEX_LITERATE
			{
			DebugLocation(1, 275);
			mHEX_LITERATE(); 

			}
			break;
		case 38:
			DebugEnterAlt(38);
			// C:\\work\\ReoScript\\ReoScript.g:1:288: STRING_LITERATE
			{
			DebugLocation(1, 288);
			mSTRING_LITERATE(); 

			}
			break;
		case 39:
			DebugEnterAlt(39);
			// C:\\work\\ReoScript\\ReoScript.g:1:304: ASSIGNMENT
			{
			DebugLocation(1, 304);
			mASSIGNMENT(); 

			}
			break;
		case 40:
			DebugEnterAlt(40);
			// C:\\work\\ReoScript\\ReoScript.g:1:315: ASSIGN_PLUS
			{
			DebugLocation(1, 315);
			mASSIGN_PLUS(); 

			}
			break;
		case 41:
			DebugEnterAlt(41);
			// C:\\work\\ReoScript\\ReoScript.g:1:327: ASSIGN_MINUS
			{
			DebugLocation(1, 327);
			mASSIGN_MINUS(); 

			}
			break;
		case 42:
			DebugEnterAlt(42);
			// C:\\work\\ReoScript\\ReoScript.g:1:340: ASSIGN_MUL
			{
			DebugLocation(1, 340);
			mASSIGN_MUL(); 

			}
			break;
		case 43:
			DebugEnterAlt(43);
			// C:\\work\\ReoScript\\ReoScript.g:1:351: ASSIGN_DIV
			{
			DebugLocation(1, 351);
			mASSIGN_DIV(); 

			}
			break;
		case 44:
			DebugEnterAlt(44);
			// C:\\work\\ReoScript\\ReoScript.g:1:362: ASSIGN_REM
			{
			DebugLocation(1, 362);
			mASSIGN_REM(); 

			}
			break;
		case 45:
			DebugEnterAlt(45);
			// C:\\work\\ReoScript\\ReoScript.g:1:373: ASSIGN_AND
			{
			DebugLocation(1, 373);
			mASSIGN_AND(); 

			}
			break;
		case 46:
			DebugEnterAlt(46);
			// C:\\work\\ReoScript\\ReoScript.g:1:384: ASSIGN_OR
			{
			DebugLocation(1, 384);
			mASSIGN_OR(); 

			}
			break;
		case 47:
			DebugEnterAlt(47);
			// C:\\work\\ReoScript\\ReoScript.g:1:394: ASSIGN_REV
			{
			DebugLocation(1, 394);
			mASSIGN_REV(); 

			}
			break;
		case 48:
			DebugEnterAlt(48);
			// C:\\work\\ReoScript\\ReoScript.g:1:405: ASSIGN_LSHIFT
			{
			DebugLocation(1, 405);
			mASSIGN_LSHIFT(); 

			}
			break;
		case 49:
			DebugEnterAlt(49);
			// C:\\work\\ReoScript\\ReoScript.g:1:419: ASSIGN_RSHIFT
			{
			DebugLocation(1, 419);
			mASSIGN_RSHIFT(); 

			}
			break;
		case 50:
			DebugEnterAlt(50);
			// C:\\work\\ReoScript\\ReoScript.g:1:433: COMMA
			{
			DebugLocation(1, 433);
			mCOMMA(); 

			}
			break;
		case 51:
			DebugEnterAlt(51);
			// C:\\work\\ReoScript\\ReoScript.g:1:439: LPAREN
			{
			DebugLocation(1, 439);
			mLPAREN(); 

			}
			break;
		case 52:
			DebugEnterAlt(52);
			// C:\\work\\ReoScript\\ReoScript.g:1:446: RPAREN
			{
			DebugLocation(1, 446);
			mRPAREN(); 

			}
			break;
		case 53:
			DebugEnterAlt(53);
			// C:\\work\\ReoScript\\ReoScript.g:1:453: LBRACE
			{
			DebugLocation(1, 453);
			mLBRACE(); 

			}
			break;
		case 54:
			DebugEnterAlt(54);
			// C:\\work\\ReoScript\\ReoScript.g:1:460: RBRACE
			{
			DebugLocation(1, 460);
			mRBRACE(); 

			}
			break;
		case 55:
			DebugEnterAlt(55);
			// C:\\work\\ReoScript\\ReoScript.g:1:467: LCURLY
			{
			DebugLocation(1, 467);
			mLCURLY(); 

			}
			break;
		case 56:
			DebugEnterAlt(56);
			// C:\\work\\ReoScript\\ReoScript.g:1:474: RCURLY
			{
			DebugLocation(1, 474);
			mRCURLY(); 

			}
			break;
		case 57:
			DebugEnterAlt(57);
			// C:\\work\\ReoScript\\ReoScript.g:1:481: COLON
			{
			DebugLocation(1, 481);
			mCOLON(); 

			}
			break;
		case 58:
			DebugEnterAlt(58);
			// C:\\work\\ReoScript\\ReoScript.g:1:487: DOT
			{
			DebugLocation(1, 487);
			mDOT(); 

			}
			break;
		case 59:
			DebugEnterAlt(59);
			// C:\\work\\ReoScript\\ReoScript.g:1:491: NOT
			{
			DebugLocation(1, 491);
			mNOT(); 

			}
			break;
		case 60:
			DebugEnterAlt(60);
			// C:\\work\\ReoScript\\ReoScript.g:1:495: INCREMENT
			{
			DebugLocation(1, 495);
			mINCREMENT(); 

			}
			break;
		case 61:
			DebugEnterAlt(61);
			// C:\\work\\ReoScript\\ReoScript.g:1:505: DECREMENT
			{
			DebugLocation(1, 505);
			mDECREMENT(); 

			}
			break;
		case 62:
			DebugEnterAlt(62);
			// C:\\work\\ReoScript\\ReoScript.g:1:515: CONDITION
			{
			DebugLocation(1, 515);
			mCONDITION(); 

			}
			break;
		case 63:
			DebugEnterAlt(63);
			// C:\\work\\ReoScript\\ReoScript.g:1:525: ELSE
			{
			DebugLocation(1, 525);
			mELSE(); 

			}
			break;
		case 64:
			DebugEnterAlt(64);
			// C:\\work\\ReoScript\\ReoScript.g:1:530: TYPE
			{
			DebugLocation(1, 530);
			mTYPE(); 

			}
			break;
		case 65:
			DebugEnterAlt(65);
			// C:\\work\\ReoScript\\ReoScript.g:1:535: TRUE
			{
			DebugLocation(1, 535);
			mTRUE(); 

			}
			break;
		case 66:
			DebugEnterAlt(66);
			// C:\\work\\ReoScript\\ReoScript.g:1:540: FALSE
			{
			DebugLocation(1, 540);
			mFALSE(); 

			}
			break;
		case 67:
			DebugEnterAlt(67);
			// C:\\work\\ReoScript\\ReoScript.g:1:546: NULL
			{
			DebugLocation(1, 546);
			mNULL(); 

			}
			break;
		case 68:
			DebugEnterAlt(68);
			// C:\\work\\ReoScript\\ReoScript.g:1:551: THIS
			{
			DebugLocation(1, 551);
			mTHIS(); 

			}
			break;
		case 69:
			DebugEnterAlt(69);
			// C:\\work\\ReoScript\\ReoScript.g:1:556: UNDEFINED
			{
			DebugLocation(1, 556);
			mUNDEFINED(); 

			}
			break;
		case 70:
			DebugEnterAlt(70);
			// C:\\work\\ReoScript\\ReoScript.g:1:566: COMMENT
			{
			DebugLocation(1, 566);
			mCOMMENT(); 

			}
			break;
		case 71:
			DebugEnterAlt(71);
			// C:\\work\\ReoScript\\ReoScript.g:1:574: LINE_COMMENT
			{
			DebugLocation(1, 574);
			mLINE_COMMENT(); 

			}
			break;
		case 72:
			DebugEnterAlt(72);
			// C:\\work\\ReoScript\\ReoScript.g:1:587: IDENTIFIER
			{
			DebugLocation(1, 587);
			mIDENTIFIER(); 

			}
			break;
		case 73:
			DebugEnterAlt(73);
			// C:\\work\\ReoScript\\ReoScript.g:1:598: NEWLINE
			{
			DebugLocation(1, 598);
			mNEWLINE(); 

			}
			break;
		case 74:
			DebugEnterAlt(74);
			// C:\\work\\ReoScript\\ReoScript.g:1:606: WS
			{
			DebugLocation(1, 606);
			mWS(); 

			}
			break;
		case 75:
			DebugEnterAlt(75);
			// C:\\work\\ReoScript\\ReoScript.g:1:609: SEMI
			{
			DebugLocation(1, 609);
			mSEMI(); 

			}
			break;

		}

	}


	#region DFA
	DFA2 dfa2;
	DFA13 dfa13;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa2 = new DFA2(this);
		dfa13 = new DFA13(this);
	}

	private class DFA2 : DFA
	{
		private const string DFA2_eotS =
			"\x1\xFFFF\x1\x3\x2\xFFFF";
		private const string DFA2_eofS =
			"\x4\xFFFF";
		private const string DFA2_minS =
			"\x2\x2E\x2\xFFFF";
		private const string DFA2_maxS =
			"\x2\x39\x2\xFFFF";
		private const string DFA2_acceptS =
			"\x2\xFFFF\x1\x1\x1\x2";
		private const string DFA2_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA2_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x2\x1\xFFFF\xA\x1",
				"",
				""
			};

		private static readonly short[] DFA2_eot = DFA.UnpackEncodedString(DFA2_eotS);
		private static readonly short[] DFA2_eof = DFA.UnpackEncodedString(DFA2_eofS);
		private static readonly char[] DFA2_min = DFA.UnpackEncodedStringToUnsignedChars(DFA2_minS);
		private static readonly char[] DFA2_max = DFA.UnpackEncodedStringToUnsignedChars(DFA2_maxS);
		private static readonly short[] DFA2_accept = DFA.UnpackEncodedString(DFA2_acceptS);
		private static readonly short[] DFA2_special = DFA.UnpackEncodedString(DFA2_specialS);
		private static readonly short[][] DFA2_transition;

		static DFA2()
		{
			int numStates = DFA2_transitionS.Length;
			DFA2_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA2_transition[i] = DFA.UnpackEncodedString(DFA2_transitionS[i]);
			}
		}

		public DFA2( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 2;
			this.eot = DFA2_eot;
			this.eof = DFA2_eof;
			this.min = DFA2_min;
			this.max = DFA2_max;
			this.accept = DFA2_accept;
			this.special = DFA2_special;
			this.transition = DFA2_transition;
		}

		public override string Description { get { return "370:4: ( ( '0' .. '9' )* '.' )?"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA13 : DFA
	{
		private const string DFA13_eotS =
			"\x1\xFFFF\x1\x2F\x1\x33\x1\x36\x1\x39\x1\x3C\x1\x3F\x1\x42\x1\x44\x1"+
			"\x46\x1\x48\x1\x4B\x1\x4D\x9\x28\x1\xFFFF\x1\x19\x1\x5E\xB\xFFFF\x4\x28"+
			"\x2\xFFFF\x1\x64\xD\xFFFF\x1\x66\x2\xFFFF\x1\x68\x12\xFFFF\x7\x28\x1"+
			"\x71\x1\x28\x1\x73\x5\x28\x2\xFFFF\x5\x28\x5\xFFFF\x5\x28\x1\x84\x2\x28"+
			"\x1\xFFFF\x1\x28\x1\xFFFF\x1\x88\x5\x28\x1\x8E\x4\x28\x1\x93\x4\x28\x1"+
			"\xFFFF\x3\x28\x1\xFFFF\x1\x9B\x3\x28\x1\x9F\x1\xFFFF\x1\xA0\x1\xA1\x1"+
			"\x28\x1\xA3\x1\xFFFF\x5\x28\x1\xA9\x1\x28\x1\xFFFF\x2\x28\x1\xAD\x3\xFFFF"+
			"\x1\x28\x1\xFFFF\x2\x28\x1\xB1\x2\x28\x1\xFFFF\x1\xB4\x1\xB5\x1\xB6\x1"+
			"\xFFFF\x2\x28\x1\xB9\x1\xFFFF\x1\xBA\x1\x28\x3\xFFFF\x1\x28\x1\xBD\x2"+
			"\xFFFF\x1\xBE\x1\x28\x2\xFFFF\x1\xC0\x1\xFFFF";
		private const string DFA13_eofS =
			"\xC1\xFFFF";
		private const string DFA13_minS =
			"\x1\x9\x1\x26\x1\x2A\x2\x3D\x1\x3C\x1\x3D\x1\x2D\x3\x3D\x1\x2B\x1\x3D"+
			"\x1\x72\x1\x61\x1\x65\x1\x61\x1\x66\x2\x65\x1\x77\x1\x68\x1\xFFFF\x1"+
			"\x78\x1\x30\xB\xFFFF\x1\x6C\x1\x61\x1\x68\x1\x6E\x1\xFFFF\x1\xA\x1\x9"+
			"\xD\xFFFF\x1\x3D\x2\xFFFF\x1\x3D\x12\xFFFF\x1\x65\x1\x73\x1\x6E\x1\x66"+
			"\x1\x72\x1\x6E\x1\x6C\x1\x30\x1\x70\x1\x30\x1\x77\x1\x6C\x1\x74\x2\x69"+
			"\x2\xFFFF\x1\x73\x1\x72\x1\x75\x1\x69\x1\x64\x5\xFFFF\x1\x61\x1\x65\x1"+
			"\x74\x1\x61\x1\x65\x1\x30\x1\x63\x1\x73\x1\xFFFF\x1\x6F\x1\xFFFF\x1\x30"+
			"\x1\x6C\x1\x75\x1\x74\x1\x6C\x1\x65\x1\x30\x1\x65\x1\x73\x1\x65\x1\x6B"+
			"\x1\x30\x1\x69\x1\x75\x1\x74\x1\x61\x1\xFFFF\x1\x74\x1\x65\x1\x72\x1"+
			"\xFFFF\x1\x30\x1\x72\x1\x63\x1\x65\x1\x30\x1\xFFFF\x2\x30\x1\x66\x1\x30"+
			"\x1\xFFFF\x1\x6E\x1\x6C\x1\x65\x1\x63\x1\x69\x1\x30\x1\x74\x1\xFFFF\x1"+
			"\x6E\x1\x68\x1\x30\x3\xFFFF\x1\x69\x1\xFFFF\x1\x75\x1\x74\x1\x30\x1\x68"+
			"\x1\x6F\x1\xFFFF\x3\x30\x1\xFFFF\x1\x6E\x1\x65\x1\x30\x1\xFFFF\x1\x30"+
			"\x1\x6E\x3\xFFFF\x1\x65\x1\x30\x2\xFFFF\x1\x30\x1\x64\x2\xFFFF\x1\x30"+
			"\x1\xFFFF";
		private const string DFA13_maxS =
			"\x1\x7E\x2\x3D\x2\x3E\x1\x3D\x1\x7C\x6\x3D\x1\x72\x1\x6F\x1\x65\x1\x75"+
			"\x1\x6E\x1\x75\x1\x65\x1\x77\x1\x68\x1\xFFFF\x1\x78\x1\x39\xB\xFFFF\x1"+
			"\x6C\x1\x61\x1\x72\x1\x6E\x1\xFFFF\x1\xA\x1\x20\xD\xFFFF\x1\x3D\x2\xFFFF"+
			"\x1\x3D\x12\xFFFF\x1\x65\x1\x73\x1\x6E\x1\x6C\x1\x72\x1\x6E\x1\x6C\x1"+
			"\x7A\x1\x70\x1\x7A\x1\x77\x1\x6C\x1\x74\x2\x69\x2\xFFFF\x1\x73\x1\x72"+
			"\x1\x75\x1\x69\x1\x64\x5\xFFFF\x1\x61\x1\x65\x1\x74\x1\x61\x1\x65\x1"+
			"\x7A\x1\x63\x1\x73\x1\xFFFF\x1\x6F\x1\xFFFF\x1\x7A\x1\x6C\x1\x75\x1\x74"+
			"\x1\x6C\x1\x65\x1\x7A\x1\x65\x1\x73\x1\x65\x1\x6B\x1\x7A\x1\x69\x1\x75"+
			"\x1\x74\x1\x61\x1\xFFFF\x1\x74\x1\x65\x1\x72\x1\xFFFF\x1\x7A\x1\x72\x1"+
			"\x63\x1\x65\x1\x7A\x1\xFFFF\x2\x7A\x1\x66\x1\x7A\x1\xFFFF\x1\x6E\x1\x6C"+
			"\x1\x65\x1\x63\x1\x69\x1\x7A\x1\x74\x1\xFFFF\x1\x6E\x1\x68\x1\x7A\x3"+
			"\xFFFF\x1\x69\x1\xFFFF\x1\x75\x1\x74\x1\x7A\x1\x68\x1\x6F\x1\xFFFF\x3"+
			"\x7A\x1\xFFFF\x1\x6E\x1\x65\x1\x7A\x1\xFFFF\x1\x7A\x1\x6E\x3\xFFFF\x1"+
			"\x65\x1\x7A\x2\xFFFF\x1\x7A\x1\x64\x2\xFFFF\x1\x7A\x1\xFFFF";
		private const string DFA13_acceptS =
			"\x16\xFFFF\x1\x23\x2\xFFFF\x1\x24\x1\x26\x1\x32\x1\x33\x1\x34\x1\x35"+
			"\x1\x36\x1\x37\x1\x38\x1\x39\x1\x3E\x4\xFFFF\x1\x48\x2\xFFFF\x1\x4A\x1"+
			"\x4B\x1\x8\x1\x2D\x1\x1\x1\x2B\x1\x46\x1\x47\x1\x2\x1\x3\x1\x13\x1\x27"+
			"\x1\x4\x1\xFFFF\x1\x5\x1\x6\x1\xFFFF\x1\x7\x1\x9\x1\x2E\x1\xF\x1\x29"+
			"\x1\x3D\x1\xB\x1\x2C\x1\xC\x1\x2A\x1\xD\x1\xE\x1\x3B\x1\x28\x1\x3C\x1"+
			"\x10\x1\x2F\x1\x12\xF\xFFFF\x1\x25\x1\x3A\x5\xFFFF\x1\x49\x1\x31\x1\x11"+
			"\x1\x30\x1\xA\x8\xFFFF\x1\x1C\x1\xFFFF\x1\x1E\x10\xFFFF\x1\x19\x3\xFFFF"+
			"\x1\x1F\x5\xFFFF\x1\x40\x4\xFFFF\x1\x15\x7\xFFFF\x1\x43\x3\xFFFF\x1\x3F"+
			"\x1\x41\x1\x44\x1\xFFFF\x1\x14\x5\xFFFF\x1\x42\x3\xFFFF\x1\x22\x3\xFFFF"+
			"\x1\x18\x2\xFFFF\x1\x1D\x1\x20\x1\x21\x2\xFFFF\x1\x17\x1\x1A\x2\xFFFF"+
			"\x1\x16\x1\x1B\x1\xFFFF\x1\x45";
		private const string DFA13_specialS =
			"\xC1\xFFFF}>";
		private static readonly string[] DFA13_transitionS =
			{
				"\x1\x2B\x1\x2A\x2\xFFFF\x1\x29\x12\xFFFF\x1\x2B\x1\xA\x1\x1A\x1\xFFFF"+
				"\x1\x28\x1\x8\x1\x1\x1\x1A\x1\x1C\x1\x1D\x1\x9\x1\xB\x1\x1B\x1\x7\x1"+
				"\x18\x1\x2\x1\x17\x9\x19\x1\x22\x1\x2C\x1\x5\x1\x3\x1\x4\x1\x23\x1\xFFFF"+
				"\x1A\x28\x1\x1E\x1\xFFFF\x1\x1F\x1\xC\x1\x28\x1\xFFFF\x1\x28\x1\xD\x1"+
				"\xE\x1\xF\x1\x24\x1\x10\x2\x28\x1\x11\x4\x28\x1\x12\x3\x28\x1\x13\x1"+
				"\x14\x1\x26\x1\x27\x1\x25\x1\x15\x3\x28\x1\x20\x1\x6\x1\x21\x1\x16",
				"\x1\x2D\x16\xFFFF\x1\x2E",
				"\x1\x31\x4\xFFFF\x1\x32\xD\xFFFF\x1\x30",
				"\x1\x34\x1\x35",
				"\x1\x37\x1\x38",
				"\x1\x3B\x1\x3A",
				"\x1\x3E\x3E\xFFFF\x1\x3D",
				"\x1\x41\xF\xFFFF\x1\x40",
				"\x1\x43",
				"\x1\x45",
				"\x1\x47",
				"\x1\x4A\x11\xFFFF\x1\x49",
				"\x1\x4C",
				"\x1\x4E",
				"\x1\x4F\xD\xFFFF\x1\x50",
				"\x1\x51",
				"\x1\x54\xD\xFFFF\x1\x52\x5\xFFFF\x1\x53",
				"\x1\x55\x6\xFFFF\x1\x56\x1\x57",
				"\x1\x58\xF\xFFFF\x1\x59",
				"\x1\x5A",
				"\x1\x5B",
				"\x1\x5C",
				"",
				"\x1\x5D",
				"\xA\x19",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x5F",
				"\x1\x60",
				"\x1\x62\x9\xFFFF\x1\x61",
				"\x1\x63",
				"",
				"\x1\x2A",
				"\x2\x2B\x2\xFFFF\x1\x2B\x12\xFFFF\x1\x2B",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x65",
				"",
				"",
				"\x1\x67",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x69",
				"\x1\x6A",
				"\x1\x6B",
				"\x1\x6C\x5\xFFFF\x1\x6D",
				"\x1\x6E",
				"\x1\x6F",
				"\x1\x70",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x72",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x74",
				"\x1\x75",
				"\x1\x76",
				"\x1\x77",
				"\x1\x78",
				"",
				"",
				"\x1\x79",
				"\x1\x7A",
				"\x1\x7B",
				"\x1\x7C",
				"\x1\x7D",
				"",
				"",
				"",
				"",
				"",
				"\x1\x7E",
				"\x1\x7F",
				"\x1\x80",
				"\x1\x81",
				"\x1\x82",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x4\x28\x1\x83\x15"+
				"\x28",
				"\x1\x85",
				"\x1\x86",
				"",
				"\x1\x87",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x89",
				"\x1\x8A",
				"\x1\x8B",
				"\x1\x8C",
				"\x1\x8D",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x8F",
				"\x1\x90",
				"\x1\x91",
				"\x1\x92",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x94",
				"\x1\x95",
				"\x1\x96",
				"\x1\x97",
				"",
				"\x1\x98",
				"\x1\x99",
				"\x1\x9A",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\x9C",
				"\x1\x9D",
				"\x1\x9E",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\xA2",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"\x1\xA4",
				"\x1\xA5",
				"\x1\xA6",
				"\x1\xA7",
				"\x1\xA8",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\xAA",
				"",
				"\x1\xAB",
				"\x1\xAC",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"",
				"",
				"\x1\xAE",
				"",
				"\x1\xAF",
				"\x1\xB0",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\xB2",
				"\x1\xB3",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"\x1\xB7",
				"\x1\xB8",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\xBB",
				"",
				"",
				"",
				"\x1\xBC",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				"\x1\xBF",
				"",
				"",
				"\xA\x28\x7\xFFFF\x1A\x28\x4\xFFFF\x1\x28\x1\xFFFF\x1A\x28",
				""
			};

		private static readonly short[] DFA13_eot = DFA.UnpackEncodedString(DFA13_eotS);
		private static readonly short[] DFA13_eof = DFA.UnpackEncodedString(DFA13_eofS);
		private static readonly char[] DFA13_min = DFA.UnpackEncodedStringToUnsignedChars(DFA13_minS);
		private static readonly char[] DFA13_max = DFA.UnpackEncodedStringToUnsignedChars(DFA13_maxS);
		private static readonly short[] DFA13_accept = DFA.UnpackEncodedString(DFA13_acceptS);
		private static readonly short[] DFA13_special = DFA.UnpackEncodedString(DFA13_specialS);
		private static readonly short[][] DFA13_transition;

		static DFA13()
		{
			int numStates = DFA13_transitionS.Length;
			DFA13_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA13_transition[i] = DFA.UnpackEncodedString(DFA13_transitionS[i]);
			}
		}

		public DFA13( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 13;
			this.eot = DFA13_eot;
			this.eof = DFA13_eof;
			this.min = DFA13_min;
			this.max = DFA13_max;
			this.accept = DFA13_accept;
			this.special = DFA13_special;
			this.transition = DFA13_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( AND | DIV | EQUALS | GREAT_EQUALS | GREAT_THAN | LESS_EQUALS | LESS_THAN | LOGICAL_AND | LOGICAL_OR | LSHIFT | MINUS | MOD | MUL | NOT_EQUALS | OR | PLUS | RSHIFT | XOR | T__95 | T__96 | T__97 | T__98 | T__99 | T__100 | T__101 | T__102 | T__103 | T__104 | T__105 | T__106 | T__107 | T__108 | T__109 | T__110 | T__111 | NUMBER_LITERATE | HEX_LITERATE | STRING_LITERATE | ASSIGNMENT | ASSIGN_PLUS | ASSIGN_MINUS | ASSIGN_MUL | ASSIGN_DIV | ASSIGN_REM | ASSIGN_AND | ASSIGN_OR | ASSIGN_REV | ASSIGN_LSHIFT | ASSIGN_RSHIFT | COMMA | LPAREN | RPAREN | LBRACE | RBRACE | LCURLY | RCURLY | COLON | DOT | NOT | INCREMENT | DECREMENT | CONDITION | ELSE | TYPE | TRUE | FALSE | NULL | THIS | UNDEFINED | COMMENT | LINE_COMMENT | IDENTIFIER | NEWLINE | WS | SEMI );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}

} // namespace  Unvell.ReoScript 
