using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("ReoScript Editor")]
[assembly: AssemblyDescription(@"ReoScript is a script language what be designed to easily invoked, executed and extended in .NET programs. 

Lexer and syntax parser generated by ANTLR. Code syntax highlight control in Script Editor named FastColoredTextBox developed by Pavel Torgashov.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximun extent prossible under the law.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("unvell")]
[assembly: AssemblyProduct("ReoScript")]
[assembly: AssemblyCopyright("Copyright © 2013 unvell, All Rights Reserved")]
[assembly: AssemblyTrademark("ReoScript")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("9dfe5212-c3f4-4772-876d-a1ecffc2517d")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.3.0.0")]
[assembly: AssemblyFileVersion("1.3.0.0")]
